# Generated by Django 5.2.1 on 2026-05-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_security_max_length'),
        ('notifications', '0001_initial'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='translation_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='translations.translationcomment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reply', '返信'), ('upvote', 'いいね'), ('mention', 'メンション')], max_length=10),
        ),
    ]
