# Generated by Django 5.2.1 on 2026-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_mention_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reply", "Reply"),
                    ("upvote", "Upvote"),
                    ("mention", "Mention"),
                ],
                max_length=10,
            ),
        ),
    ]
