# Generated by Django 5.2.1 on 2026-08-01 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0016_comment_comment_location_recent_idx_and_more"),
        ("notifications", "0003_alter_notification_notification_type"),
        ("translations", "0005_translationlibraryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"], name="notif_recipient_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="notif_unread_recent_idx",
            ),
        ),
    ]
