# Generated by Django 5.2.1 on 2026-08-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notification_notif_recipient_recent_idx_and_more"),
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="qa.answer",
            ),
        ),
    ]
