# Generated by Django 5.2.1 on 2026-09-08 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0018_remove_comment_comment_qa_recent_idx_and_more"),
        ("notifications", "0005_notification_answer"),
        ("qa", "0002_question_search_indexes"),
        ("translations", "0006_project_search_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_recipient_recent_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_unread_recent_idx",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at", "-id"],
                name="notif_recipient_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at", "-id"],
                name="notif_unread_recent_idx",
            ),
        ),
    ]
