"""Text material for making the site look like it is used by English speakers."""

LANG = "en"

# ── People ──────────────────────────────────────────────────────────────────
FAMILY_NAMES = [
    "whitfield",
    "chen",
    "okonkwo",
    "hartwell",
    "reed",
    "adeyemi",
    "kowalski",
    "steinberg",
    "brooks",
    "fletcher",
    "malone",
    "martinez",
    "osei",
    "thornton",
    "jacob",
    "sullivan",
    "nguyen",
    "ashford",
    "kamau",
    "goldfarb",
    "dupont",
    "walker",
    "diallo",
    "mcallister",
    "park",
    "obi",
    "brunner",
    "lindqvist",
    "oduya",
    "carrington",
    "mbeki",
    "santos",
    "delacroix",
    "hughes",
    "abadi",
    "petrov",
    "ferreira",
    "kaplan",
    "oyelaran",
    "vance",
]

GIVEN_NAMES = [
    "james",
    "sarah",
    "michael",
    "emily",
    "thomas",
    "grace",
    "daniel",
    "rachel",
    "elijah",
    "naomi",
    "patrick",
    "david",
    "abigail",
    "caleb",
    "priya",
    "margaret",
    "deborah",
    "nathaniel",
    "lydia",
    "ben",
    "clara",
    "jerome",
    "amara",
    "ruth",
    "jonathan",
    "esther",
    "felix",
    "hana",
    "isaiah",
    "miriam",
    "andrew",
    "phoebe",
    "simon",
    "tabitha",
    "gideon",
    "hannah",
    "silas",
    "joanna",
    "amos",
    "keziah",
]

BIO_ROLES = [
    "Senior pastor at a mid-sized congregation",
    "PhD candidate in New Testament studies",
    "Youth group leader and homeschool parent",
    "Professor of biblical archaeology",
    "Hospice chaplain",
    "Catholic convert and Dominican lay associate",
    "Interfaith dialogue facilitator",
    "Methodist pastor of twenty years",
    "Recovering skeptic and new believer",
    "Priest and Scripture scholar",
    "Worship leader and songwriter",
    "Pediatric nurse and Pentecostal believer",
    "Seminary student in systematic theology",
    "Syrian Orthodox Christian",
    "Software engineer and lay preacher",
    "Anglican lay reader in a rural parish",
    "Bible translator working in East Africa",
    "Messianic Jewish teacher",
    "Reformed Christian reading Calvin alongside the text",
    "Retired schoolteacher who started reading at sixty-five",
    "Muslim-background believer",
    "Biblical counselor and women's study leader",
    "Church planter and pastor's kid",
    "Theologian writing on women in the early church",
    "Swiss Reformed pastor with an interest in the Apocrypha",
    "Lutheran and contemplative prayer practitioner",
    "Evangelist and radio host",
    "Retired nun and spiritual director",
    "Classics graduate reading the Bible as literature",
    "Prison chaplain",
]

BIO_INTERESTS = [
    "The Psalms are my daily anchor.",
    "I care deeply about the non-canonical texts getting a fair hearing.",
    "I compare translations obsessively and take too many notes.",
    "Job is the most honest book in the canon and I will defend that.",
    "I read Revelation as pastoral poetry, not prediction.",
    "The Septuagint keeps surprising me.",
    "I want scripture in plain language without losing its edge.",
    "I'm working through the whole Bible for the first time.",
    "Paul's argumentative structure fascinates me.",
    "I collect every passage about food and fasting.",
    "The book of Enoch changed how I read Jude.",
    "I sit with one verse a day and nothing more.",
    "I'm interested in how the same texts read differently across traditions.",
    "Textual variants are my idea of a good evening.",
    "I write hymns from the prophets.",
    "I study how women are portrayed and who did the portraying.",
    "I read the Gospels looking for what Matthew leaves out.",
    "I care about how scripture is used to hurt people.",
    "I keep a notebook of every question I can't answer.",
    "Thomas and the canonical Gospels side by side is my current project.",
    "I read at night when the house is finally quiet.",
    "I came for the history and stayed for something else.",
    "Suffering is the thread I keep pulling on.",
    "I've read the whole thing three times and understood it less each time.",
    "I mostly lurk and read other people's notes.",
]

BIO_CLOSERS = [
    "Happy to be corrected.",
    "Always up for a good argument about a preposition.",
    "Say hello if we're reading the same book.",
    "Still learning. Still surprised.",
    "",
    "",
    "",
]

# ── Verse comments ──────────────────────────────────────────────────────────
COMMENT_SENTENCES = [
    "This verse carried me through the worst year of my life, and I keep coming back to it.",
    "The Greek word here is agape, which is less a feeling than a decision to lay yourself down.",
    "The Hebrew shalom means wholeness with nothing missing, which our word 'peace' barely touches.",
    "Put this back in its first-century Jewish setting and the sharpness of it comes right back.",
    "Our pastor preached on this last Sunday and I came here to dig further.",
    "Reading the KJV next to a modern translation shows how much the emphasis shifts.",
    "The 'you' in the original is plural. He is addressing a community, not an individual.",
    "The verb is present tense, so this reads as ongoing practice rather than a one-time act.",
    "Read the two verses on either side of this and the meaning changes completely.",
    "The manuscript tradition splits here, and the footnotes are worth an hour of your time.",
    "When I explain this to children I always reach for something they can hold.",
    "Paul wrote this from prison, which reframes every line of it.",
    "I read this differently depending on the kind of week I've had.",
    "It's poetry, so read it out loud. It stops being abstract immediately.",
    "I memorized this at fourteen and it still surfaces uninvited.",
    "The light imagery here runs through the whole book as a deliberate thread.",
    "This was read at my grandmother's funeral and I can still hear the room.",
    "Some translations say mercy, others say steadfast love, and the difference matters.",
    "The same phrasing shows up in the prophets, which cannot be accidental.",
    "This verse gets quoted constantly by people who have not read the paragraph around it.",
    "I asked three ministers what this meant and got three answers.",
    "Setting the theology aside for a moment, it's simply a beautiful sentence.",
    "There's a close parallel in 1 Enoch, which suggests a shared vocabulary.",
    "'Righteousness' is such a stiff word in English that younger readers just bounce off it.",
    "The Septuagint and the Masoretic text disagree here and commentators handle it differently.",
    "Take this instruction literally and your whole life has to be rearranged.",
    "I understood nothing the first time and then it landed a decade later.",
    "A child in my class asked a question about this and I had no answer.",
    "The original has a sound repetition that no translation preserves.",
    "I have heard many sermons built on this verse and they cannot all be right.",
    "I would be careful about handing this verse to someone who is grieving.",
    "'Believe' here is continuous, not a single moment of decision.",
    "Trace the same root through the Old Testament and the range is enormous.",
    "This verse makes me think about small ordinary choices, not big dramatic ones.",
    "The older English versions have a music to them that I still prefer.",
    "I compared three commentaries and none of them agreed.",
    "'World' here means the human order, not the planet.",
    "The entire argument of the book is compressed into this one line.",
    "This is often used as a call to worship, and it works well there.",
    "The Latin tradition shaped how this got rendered into every modern language.",
    "Grammatically it can go either way, and translators simply have to choose.",
    "I have this taped inside a kitchen cupboard where I see it every morning.",
    "In Greco-Roman culture a gift created obligation, so 'grace' carries weight we miss.",
    "Compare this with the parallel account and the authors' priorities separate cleanly.",
    "I have sat with people at the end of their lives who needed exactly this sentence.",
    "It's a contested verse and I've decided not to fight about it anymore.",
    "A church I loved split over this passage, so I read it carefully now.",
    "Some scholars think a copyist's slip became the standard reading here.",
    "For such a short line it carries an extraordinary amount.",
    "I wrote out the surrounding verses by hand to prepare a sermon on this.",
    "This is the passage that let me keep reading while still doubting.",
    "There's an alternate reading in the margin that scans better to me.",
    "It quotes the Old Testament but uses it in a nearly opposite sense.",
    "Remove this verse and the book becomes a different book.",
    "The same word means the opposite thing two books later, which is maddening.",
    "Every year around this season I find myself back here.",
    "It works as a prayer without any alteration at all.",
    "The word rendered 'heart' means the seat of the will, not the emotions.",
    "I like imagining how the first community to hear this reacted.",
    "By the standards of the time this instruction was not merely hard but absurd.",
    "I had skimmed past this for years until someone pointed it out.",
    "A lot of people use this verse to beat themselves up, and that troubles me.",
    "Read aloud, you can almost hear the writer breathing.",
    "Read alongside the apocrypha you see both why it was included and why others weren't.",
    "The translation is old enough that the sense has quietly inverted.",
    "This is the kind of line you understand by living it, not by studying it.",
    "Specialists still disagree, so I'd rather not state anything too firmly.",
    "Honestly my first reaction here is anger, not forgiveness.",
    "Preachers avoid this one because it is genuinely hard to handle well.",
    "What snagged me at twenty is not what snags me now.",
    "Even in Greek it is unclear who the subject is.",
    "Read it together with the parable that follows immediately after.",
    "I translated this verse for a project and spent three weeks on one word.",
    "'Wait' here carries the tension of expectation, not passivity.",
    "The style shifts abruptly here, which is why some argue it's a quoted source.",
    "I stopped attending years ago and this is one of the few lines I kept.",
    "It reads smoothly in English but the underlying sentence is rough and knotted.",
    "Knowing the history of the arguments about this verse changes how you read it.",
    "I take this as a statement of hope rather than a rule of conduct.",
    "The phrasing is lifted straight out of the Psalms.",
    "'Hear' includes obeying, which English loses entirely.",
    "Reading this in Japanese made it a different story to me.",
    "My daughter asked something about this that no adult would think of.",
    "Some argue this is standard letter-writing convention with no special meaning.",
    "Quoted so often that it has drifted a long way from its original sense.",
    "I would not be doing the work I do now without this verse.",
    "The chapter break here is unfortunate; it should be read straight through.",
    "My commentary gives this one line, which only makes me more curious.",
    "I know exactly one person who actually lives this way.",
    "The choice of word reveals the theological position of the whole translation.",
    "I looked it up and was surprised how few times the word occurs.",
    "Whether you read it as promise or command changes the entire landscape.",
    "The prayer book uses a different rendering that I've grown fond of.",
    "This was the passage read on the first day I ever walked into a church.",
    "I can't follow the scholarly arguments, but I know this line helped me.",
]

REPLY_SENTENCES = [
    "I had never considered reading it that way. Thank you.",
    "I agree broadly, though the preceding verse complicates it a little.",
    "Could you point me to a source? I couldn't find this in my commentary.",
    "I read it the other way round, so perhaps both are open.",
    "I checked the Greek and the form is exactly as you describe.",
    "If that's right, I'm not sure the second half of the sentence holds together.",
    "This is a clear explanation and I'd like to use it in our study group.",
    "Reading the same thing in another translation shifts it again.",
    "To add to this: the parallel passage renders the same word differently.",
    "We never touch this passage at my church, so this is useful.",
    "I think specialists are genuinely divided on that point.",
    "That angle is new to me and I want to sit with it for a while.",
    "I got stuck at exactly the same place for a long time.",
    "Grammatically possible, but is it plausible in context?",
    "I tried this in a sermon and the response was remarkable.",
    "Thanks, though I think that rendering leans a bit too far into paraphrase.",
    "I saw a similar argument on another passage. I'll try to find it.",
    "Writing as someone who disagrees, and meaning no offense by it.",
    "I think you're right, and I also think it's nearly impossible to do.",
    "Coming back to the original comment, the question may be simpler than this.",
    "I read as a layperson so I can't follow all of the technical argument.",
    "This feels less like a translation problem and more like an assumption problem.",
    "Fair. I hadn't seen it until you said it.",
    "Slight tangent, but the same phrase turns up in the apocrypha.",
    "I'll agree with the second half and reserve judgment on the first.",
]

CHAPTER_SENTENCES = [
    "Read this chapter in one sitting; breaking it up destroys the argument.",
    "It's built in three movements with the main claim at the centre.",
    "Our study group spent four weeks here and we're not finished.",
    "The chapter division is a later convenience; the thought carries over from before.",
    "There are more than ten Old Testament citations in this chapter alone.",
    "I get stuck in the second half every single time.",
    "This chapter is the reason I started learning the original languages.",
    "One word recurs throughout, which tells you the structure is deliberate.",
    "Rereading it in a different version changed my sense of the whole chapter.",
    "It gets read at funerals constantly, well away from its actual context.",
    "The opening and closing correspond, forming a frame around the middle.",
    "The last section is absent from some manuscripts.",
    "The opening verses may have circulated separately as a poem.",
    "I abandoned my first read-through in this chapter and now it's a favourite.",
    "The ethical argument here maps onto contemporary debates almost directly.",
    "It's hard to teach to children and I always end up skipping parts.",
]

BOOK_SENTENCES = [
    "Reading the whole book straight through exposed how much I'd misread in fragments.",
    "The entire theme is compressed into the opening lines.",
    "Authorship is still argued about, but that changes nothing about its worth.",
    "This book takes a markedly different angle from the others and goes deeper for it.",
    "Set it beside the texts that didn't make the canon and the selection logic emerges.",
    "I'd hand this book first to anyone who is full of doubt.",
    "The editorial seams are visible, and that's part of what makes it interesting.",
    "I diagrammed the structure and found it almost perfectly symmetrical.",
    "Learn the political situation it was written into and it becomes another book entirely.",
    "It's notoriously hard to translate and the English versions diverge widely.",
    "It's short, and it took me longer than anything else.",
    "I finished it and couldn't do anything else for the rest of the day.",
]

# ── Q&A ─────────────────────────────────────────────────────────────────────
QUESTION_PAIRS = [
    (
        "Eye of a needle: literal, or a gate in Jerusalem?",
        "Does the 'eye of a needle' refer to an actual needle or to a gate? I've heard both explanations confidently asserted and I'd like to know what the evidence actually supports.",
    ),
    (
        "Reconciling Paul on the role of women",
        "How do we hold together the passages restricting women's speech with the same author naming women as coworkers and leaders?",
    ),
    (
        "Best commentaries without knowing Greek or Hebrew",
        "I want serious engagement with the text but I have no original languages. What should I be reading?",
    ),
    (
        "How much did the New Testament writers know of Enoch?",
        "Jude quotes it directly. How widely was 1 Enoch known and read in the early communities?",
    ),
    (
        "What do I do with the imprecatory Psalms?",
        "The Psalms that call down destruction on enemies disturb me. Is there a responsible way to pray them?",
    ),
    (
        "Literacy in first-century Palestine",
        "What do we actually know about literacy rates, and how should that shape how we read the Gospels?",
    ),
    (
        "Why does Mark have more than one ending?",
        "My study Bible notes that the earliest manuscripts end at verse 8. Can someone explain the situation?",
    ),
    (
        "Is reading the apocrypha discouraged?",
        "I've been reading Thomas and Enoch and people at church react oddly. Is there an actual objection here?",
    ),
    (
        "Which translation should I settle on?",
        "I keep switching between versions and never finishing anything. How do people choose?",
    ),
    (
        "Did Jesus claim to be God?",
        "The Gospels seem to phrase this quite differently from each other. How should I hold them together?",
    ),
    (
        "Is Revelation about the future?",
        "I grew up with an end-times reading and recently heard it described as protest literature. Which is it?",
    ),
    (
        "Does fasting still make sense?",
        "There's a lot of fasting in scripture. What place should it have now, if any?",
    ),
    (
        "Is the tithe a New Testament teaching?",
        "The ten percent figure gets quoted often. Where does it actually come from?",
    ),
    (
        "Can suffering be said to have meaning?",
        "Job doesn't resolve it for me. I'd like to hear how others hold this.",
    ),
    (
        "What does the Bible actually say about the afterlife?",
        "How much description is there, and where? I suspect less than people assume.",
    ),
    (
        "Should Christians keep the Sabbath?",
        "My job requires weekend work. How have others thought about this?",
    ),
    (
        "How do you handle Gospel discrepancies?",
        "The same event is reported differently. Does this create a problem, and if not, why not?",
    ),
    (
        "Do parables have a single correct meaning?",
        "Every commentary offers a different reading. Is one of them right?",
    ),
    (
        "How much of the Law still applies?",
        "Food rules, purity rules, festival rules. Where is the line drawn and on what basis?",
    ),
    (
        "What kind of document is the Gospel of Thomas?",
        "I read it and the atmosphere is completely different. What am I actually reading?",
    ),
    (
        "Is there a better order to read the Bible in?",
        "Genesis-first defeated me twice. What order do people recommend?",
    ),
    (
        "How do I get into the prophets?",
        "They feel impenetrable without background. Where should I start?",
    ),
    (
        "Is Proverbs just practical advice?",
        "It reads like a manual for getting ahead. Is that a misreading?",
    ),
    (
        "Do Paul and James contradict each other?",
        "Faith and works appear to be argued in opposite directions.",
    ),
    (
        "What do I do when I find a contradiction?",
        "I noticed something that doesn't line up and I don't know what to do with it.",
    ),
    (
        "Does reading alone, outside a church, count?",
        "Is there something essential I'm missing by reading on my own?",
    ),
    (
        "How do I teach the violent passages to children?",
        "I freeze every time a question comes up about the conquest narratives.",
    ),
    (
        "What exactly is the Holy Spirit?",
        "The doctrinal formulas don't give me anything I can grasp.",
    ),
    (
        "What is the Septuagint and why does it matter?",
        "It comes up constantly in footnotes and I've never understood its significance.",
    ),
    (
        "How do the Dead Sea Scrolls relate to the Bible?",
        "What did they actually change about our understanding?",
    ),
    (
        "Can the resurrection be discussed historically?",
        "I'd like to understand the line between historical claim and confession of faith.",
    ),
    (
        "How should I take the miracle accounts?",
        "I can't take them at face value. Does that disqualify me?",
    ),
    (
        "What does scripture say about communion?",
        "Traditions differ enormously. What does the text itself support?",
    ),
    (
        "How do I find the verse behind a hymn?",
        "Is there a good method for tracing hymn texts back to scripture?",
    ),
    (
        "How should the passages about same-sex relations be read?",
        "I want to understand the interpretive questions before forming a view.",
    ),
    (
        "Why are there two creation accounts?",
        "Genesis 1 and 2 read very differently. What's the standard explanation?",
    ),
    ("Was the exodus a historical event?", "What's the state of the archaeological discussion?"),
    (
        "Who wrote the Pentateuch?",
        "I've encountered the documentary hypothesis and would like a fair summary.",
    ),
    (
        "What's the difference between the canons?",
        "Catholic, Orthodox and Protestant Bibles differ. How did that happen?",
    ),
    (
        "How literally should Genesis 1 be read?",
        "I'd like to understand the range of serious positions, not just the loudest ones.",
    ),
]

ANSWER_SENTENCES = [
    "Most scholars today read this figuratively, though a literal reading has serious defenders.",
    "The short answer is that scripture itself does not settle this; several readings coexist.",
    "Knowing the situation of the community it was written for makes this much clearer.",
    "The original language has a wider range of meaning than the English suggests.",
    "This is how my tradition explains it, but it is not the only explanation available.",
    "Practically: check the immediate context first, then compare the parallel passages.",
    "There's a long history here, with the argument running from the fourth century onward.",
    "In practice, starting small is the only approach I've seen actually work.",
    "You are far from alone in this. I had no answer for a very long time.",
    "Commentaries genuinely diverge here, so read two or three rather than one.",
    "I'd start with your own reading before reaching for anyone's doctrinal summary.",
    "Honestly, I don't think a clean answer to this exists.",
    "Tracing how the early church handled it locates the modern debate quite usefully.",
    "Sometimes changing translation dissolves the question entirely.",
    "The answer differs depending on whether you're asking historically or confessionally.",
    "It's fine to carry the question unresolved for a while.",
    "I'll list some sources below in case you want to go further.",
    "I'm a minister and my honest answer to this is that I don't know.",
    "In my experience the practice changes before the understanding does.",
    "This may be a minority reading, but here is how I take it.",
    "Worth adding: a non-canonical text treats the same theme and the comparison is illuminating.",
    "It may be worth questioning the premise of the question itself.",
    "Traditions answer this very differently, so ask in your own community too.",
    "Briefly: both are right. At length: it's a book.",
    "I heard a sermon on precisely this and I'll summarize how it was framed.",
    "The grammatical explanation is long, so I'll just give the conclusion.",
    "Note that interpretation has already entered at the translation stage here.",
    "If you're not in a hurry, come back to this in a year.",
    "I walked the same road. These days I care more about the question than the answer.",
    "I've written this confidently but I would genuinely welcome disagreement.",
]

# ── Articles ────────────────────────────────────────────────────────────────
ARTICLE_TITLE_HEADS = [
    "Reading",
    "Against",
    "The Silence in",
    "On Forgiving",
    "Notes on",
    "Late Night",
    "Letting Go of",
    "At the Edge of",
    "Holding the Question in",
    "Unprayable",
    "Anger and",
    "The Small Voice of",
    "Halfway Through",
    "From the Kitchen Table:",
    "The Unfinished",
    "Still Broken:",
    "The Work of Waiting in",
    "White Space in",
    "The Long Way to",
    "Quiet in",
]

ARTICLE_TITLE_TAILS = [
    "the Sermon on the Mount",
    "Job's Silence",
    "the Psalms",
    "the Prodigal Son",
    "Paul's Letters",
    "the Morning of Genesis",
    "Enoch's Vision",
    "the Sayings of Thomas",
    "the City in Revelation",
    "the Exodus Road",
    "Ruth's Choice",
    "Jeremiah's Lament",
    "Mary's Song",
    "Peter's Denial",
    "the Words from the Cross",
    "the Sabbath",
    "the Day of Fasting",
    "the Shepherd Psalm",
    "Holy Week",
    "Easter Morning",
]

ARTICLE_SUMMARIES = [
    "An attempt to read a famous passage all the way through without lifting it out of context.",
    "How I finally made peace with a passage I avoided for years.",
    "What came into view when I set three translations side by side.",
    "A direct look at the part of this text that rarely gets preached.",
    "Written out of a failed attempt to explain this passage to a child.",
    "Notes from reading a canonical and a non-canonical text next to each other.",
    "A by-product of sermon preparation, reworked into something readable.",
    "Written from the experience of being hurt by words drawn from this passage.",
    "One verse, read slowly, with one word held up to the light.",
    "I stopped here in the middle of a read-through, and wrote from the stopping.",
    "No conclusions. The aim was only to get the shape of the question right.",
    "Moving back and forth between an ordinary week and an ancient text.",
]

ARTICLE_HEADINGS = [
    "Before we start",
    "The text itself",
    "Comparing translations",
    "Following the context",
    "One word that snags",
    "Another way to read it",
    "In its own century",
    "In an ordinary week",
    "Leaving the question open",
    "Anticipating the objection",
    "Closing",
    "A note",
    "What I read",
]

ARTICLE_PARAGRAPHS = [
    "The first time I read this passage I understood nothing at all. I carried that incomprehension around for years, and then one afternoon it turned slightly, the way a key turns, and something opened. What follows is an attempt to describe the turn.",
    "Let me set the terms. This is not an argument about doctrinal correctness. It is one reader's account of what the text can be made to yield. I am going to leave the ending open on purpose.",
    "Put the translations side by side and the same verse arrives differently each time. One is soft, another is severe, and the original is a third thing that is neither. That difference is itself a way in.",
    "Pull a single verse out of its paragraph and you can make it say almost anything. This particular verse has been made to say a great deal. Which is precisely why it deserves to be read with what stands on either side of it.",
    "Now set it back into its own century. What was the community that first heard this actually worried about? Simply imagining that changes the temperature of every line.",
    "There are obvious objections, and I don't hold this reading with much confidence. What I would defend is narrower: that the text leaves room for it.",
    "A word about ordinary life. I think about this passage in the kitchen and on the train, almost never in a pew. I have come to suspect that is not accidental.",
    "Reading the non-canonical material alongside this shows how wide the shared vocabulary of the period really was. Looking only at what was eventually collected hides that width entirely.",
    "How you render this one word determines the meaning of the whole paragraph. A translator has to decide, and the decision is already an interpretation. Readers deserve to know that a decision was made.",
    "Here is the conclusion, which is not an answer. I have decided to read this as a promise rather than a command, for the plain reason that I can live inside the first reading and not the second. Whether that is a legitimate reason I genuinely do not know.",
    "A short detour. There is a passage elsewhere with the same shape though no direct connection, and setting them next to each other makes the writers' different concerns visible.",
    "Some people are consoled by this verse and others are wounded by it, often in the same room. The writer almost certainly did not anticipate that. It is left for readers to carry.",
    "I went through several scholarly treatments and found nothing decisive. On reflection, the absence of anything decisive may be the most appropriate result this passage could produce.",
    "Finally, back to the text. No amount of commentary competes with the texture of the sentences themselves. Read it out loud once before you read anything else about it.",
    "This is where I stopped. I could not go forward, so I stayed with the same few lines for a long time. I have come to think the staying was the point.",
]

ARTICLE_COMMENT_SENTENCES = [
    "A genuinely rewarding read. The way the citations are used is especially good.",
    "I've been stuck at the same passage, so I read this with a lot of recognition.",
    "I can't sign up to the conclusion, but it's carefully argued.",
    "Would you share what you were reading alongside this?",
    "This angle hadn't occurred to me. I'm going back to reread.",
    "I wondered about the translation used in the block quote. Does another version change it?",
    "May I share this with my study group?",
    "The last section moves quite fast. I'd happily read twice as much.",
    "Hoping there's a second part.",
    "Let me put the opposing case briefly.",
    "I tried this and found it worked exactly as described.",
    "The rhythm of the writing carried me as much as the argument did.",
    "Small thing: one of the chapter numbers looks off by one.",
    "I have been looking for writing like this. Thank you.",
]

# ── Plans ───────────────────────────────────────────────────────────────────
PLAN_TITLE_HEADS = [
    "A First Look at",
    "Nights in",
    "Mornings in",
    "Quiet",
    "Reading with Questions:",
    "In Hard Seasons:",
    "A Journey Through",
    "Kitchen Table",
    "Doubting Through",
    "Aloud in",
    "Beginners'",
    "Returning to",
    "Across the Canon:",
    "Seasonal",
    "For Working People:",
]

PLAN_TITLE_TAILS = [
    "the Gospels",
    "the Psalms",
    "Paul's Journeys",
    "Genesis",
    "the Prophets",
    "Holy Week",
    "Eastertide",
    "the Wisdom Books",
    "the Apocrypha",
    "Revelation",
    "the Letters",
    "Exodus",
    "Job",
    "the Twelve",
    "Acts",
]

PLAN_DESCRIPTIONS = [
    "Built for people just starting out, with daily portions small enough to actually finish.",
    "Designed for reading alone at night. Read it out loud if you can.",
    "Sets canonical and non-canonical texts side by side, so you can feel the difference for yourself.",
    "Made for people going through something hard. There is no need to keep pace.",
    "For anyone who has abandoned a read-through more than once. The order has been rearranged.",
    "Intended for small groups, with discussion in mind rather than solo reading.",
    "The daily portion is deliberately short. Spend the time thinking rather than reading.",
    "Follows the shape of the church year.",
    "Switches translations along the way so you notice the texture of the language.",
    "The point is to keep the question open. No answers are supplied.",
    "Short on weekdays, longer at the weekend, for people with full-time work.",
    "A full year through the whole Bible. Stopping partway is a legitimate outcome.",
]

PLAN_DAY_TITLES = [
    "Beginning",
    "Asking",
    "Reading the Silence",
    "Light and Dark",
    "Setting Out",
    "In the Wilderness",
    "A Word of Promise",
    "The Lament",
    "On Forgiving",
    "At the Table",
    "Before Dawn",
    "The Way Back",
    "A Day of Fasting",
    "Called",
    "Waiting",
    "The Fork in the Road",
    "Reading a Letter",
    "A New Name",
    "The Final Vision",
    "Toward Quiet",
]

PLAN_DEVOTIONALS = [
    "Today's portion is short. Read it twice without hurrying, and write down whatever snagged you on the second pass.",
    "If something is unclear, keep going rather than stopping. You are allowed to carry the confusion forward.",
    "Today you read a canonical and a non-canonical text together. Notice how differently the same theme is handled.",
    "This passage means different things depending on where the reader is standing. Notice where you are standing.",
    "Read it aloud. The repetitions and the rhythm do not survive silent reading.",
    "There is difficult material here. If it is too much, skip it. Choosing not to read is also a way of reading.",
    "Switch translations today. Pick one you never use and mark anything that feels wrong.",
    "This portion contains a very famous line. Forget that it is famous and read it in its paragraph.",
    "A short chapter, but worth a whole day. Copy it out by hand if you have time.",
    "This continues yesterday. Check whether what caught you yesterday looks different now.",
    "Today's reading is frequently argued about. Before reaching a view, note only what the text says.",
    "When you finish, summarize it in one line of your own words. Failing to is also useful information.",
]

PLAN_NOTES = [
    "Days 5 and 6 were published in the wrong order. Apologies to anyone already reading.",
    "The translation specified for one day was wrong and has been corrected. No content changed.",
    "Rewrote the note for day 12 after a reader pointed out an error.",
    "",
    "",
]

# ── Translation projects ────────────────────────────────────────────────────
PROJECT_NAME_HEADS = [
    "Contemporary English",
    "Plain Language",
    "A Reader's",
    "Children's",
    "Spoken",
    "Poetic",
    "Annotated",
    "Collaborative",
    "Interlinear-Friendly",
    "Read-Aloud",
]

PROJECT_DESCRIPTIONS = [
    "Avoids specialist religious vocabulary in favour of the words people actually use.",
    "Written for new readers and for people reading in a second language.",
    "Made to be read out loud in public worship and understood by ear.",
    "Aimed at children reading independently.",
    "Keeps the original syntax as far as English will bear it.",
    "Treats the poetry as poetry, preserving line breaks and rhythm.",
    "Records the reasoning behind each word choice so it can be checked later.",
    "Divided among several translators, with weekly meetings to align the voice.",
    "Designed to sit beside the original text on the page.",
    "Keeps what works in the older versions and replaces only what has aged badly.",
]

UNIT_BODIES = [
    "This is how God loved the world: he gave his only Son.",
    "In the beginning was the Word, and the Word was with God, and the Word was God.",
    "I am the way, the truth, and the life.",
    "You are the light of the world. A city built on a hill cannot be hidden.",
    "Blessed are the poor in spirit, for the kingdom of heaven belongs to them.",
    "Blessed are those who mourn, for they will be comforted.",
    "Blessed are the gentle, for they will inherit the earth.",
    "Blessed are those who hunger and thirst for righteousness, for they will be filled.",
    "Blessed are the merciful, for they will receive mercy.",
    "Blessed are the pure in heart, for they will see God.",
    "Blessed are the peacemakers, for they will be called children of God.",
    "Love is patient, love is kind. It does not envy and it does not boast.",
    "The Lord is my shepherd; there is nothing I lack.",
    "Your word is a lamp for my feet and a light on my path.",
    "Come to me, all of you who are worn out and weighed down, and I will give you rest.",
    "Do not be anxious about anything; in everything, by prayer, make your requests known.",
    "The light shines in the darkness, and the darkness has not overcome it.",
    "Ask, and it will be given to you. Search, and you will find.",
]

PROJECT_COMMENT_SENTENCES = [
    "One word in the original, but English needs two here without sounding stilted.",
    "'Love' is too broad a word. Can we choose something context-specific?",
    "Fewer Latinate words would make this land better when read aloud.",
    "The register shifts in this verse. We should agree a policy and apply it throughout.",
    "We're split between formal equivalence and readability. Let's settle it in the meeting.",
    "I've ended up with the same wording as an existing version and I can't better it.",
    "Read aloud, this word order is hard to follow.",
    "The wordplay in the original doesn't survive. Should it go in a footnote?",
    "If children are the audience, this vocabulary is too high.",
    "This term carries denominational baggage, so let's choose carefully.",
    "My section is submitted and ready for review.",
    "Reviewed. Two suggestions left inline.",
    "Reading the whole thing through, the handling of pronouns is inconsistent.",
    "We need the translation policy written down or newcomers will have nothing to work from.",
    "This is a hard verse. Could a few of us draft alternatives?",
]
