# Generated by Django 5.2.1 on 2026-05-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='verse',
        ),
    ]
