import type { PlanVisibility } from "@/lib/types";

export const planUiText = (lang: "ja" | "en") => lang === "ja" ? {
  plansTitle: "読書プラン",
  plansDescription: "書をまたいで章を並べ、日ごとに読んでいく道すじです。",
  newPlan: "新しいプラン",
  readingPlans: "読んでいるプラン",
  myPlans: "自分のプラン",
  myPlansDescription: "下書きも含めて、自分が作ったプラン。",
  publicPlans: "公開されたプラン",
  publicPlansDescription: "誰でも読めるプラン。",
  noPlans: "まだプランがありません。",
  noPublicPlans: "公開されたプランはまだありません。",
  loadErrorTitle: "読書プランを読み込めませんでした",
  loadErrorDescription: "通信状態を確認して、もう一度お試しください。",
  retry: "もう一度試す",
  visibilityLabel: (visibility: PlanVisibility) => visibility === "public" ? "公開" : visibility === "unlisted" ? "限定公開" : "下書き",
  visibilityOptions: [
    { value: "private" as const, label: "下書き" },
    { value: "unlisted" as const, label: "限定公開" },
    { value: "public" as const, label: "公開" },
  ],
  dayCount: (count: number) => `${count}日`,
  readerCount: (count: number) => `${count}人が読書中`,
  newTitle: "新しいプラン",
  newDescription: "題を決めると下書きができます。日や章はあとから足せます。",
  titleLabel: "題",
  titlePlaceholder: "例: 7日で読む終わりの日",
  create: "作りはじめる",
  creating: "作成中…",
  cancel: "やめる",
  createError: "プランを作れませんでした。もう一度お試しください。",
  createLoginRequired: "プランを作るにはログインが必要です。",
  login: "ログインする",
  discardNewTitle: "作りかけのプランを破棄しますか？",
  discardNewDescription: "入力した題は保存されません。",
  discardNewConfirm: "破棄する",
  unreadableTitle: "このプランは読めません",
  unreadableDescription: "削除されたか、公開範囲が変更された可能性があります。",
  backToPlans: "プランの一覧へ",
  edit: "編集する",
  ownerNote: "作った人からの注記",
  startLoginRequired: "読み始めるにはログインが必要です。",
  start: "読み始める",
  resume: "また読み始める",
  reading: "読書中",
  today: (day: number) => `今日は${day}日目`,
  progress: (done: number, total: number) => `${done} / ${total} 日ぶん読み終わり`,
  restart: "最初からやり直す",
  stop: "やめる",
  restartTitle: "最初からやり直しますか？",
  restartDescription: "読み終えた印がすべて消えて、今日から数え直します。",
  restartConfirm: "やり直す",
  actionError: "操作を完了できませんでした。もう一度お試しください。",
  dayNumber: (day: number) => `第${day}日`,
  completed: "読み終わり ✓",
  markCompleted: "読み終えた",
  // 章ごとの印の読み上げ名。印は丸だけで文字を持たないので、ここが唯一の説明になる。
  markReadingCompleted: (reading: string) => `${reading}を読み終えたと記録`,
  unmarkReadingCompleted: (reading: string) => `${reading}の読み終わりを取り消す`,
  // その日の見出しの右に出す進み具合。押すものではないので数字だけにする。
  dayReadingCount: (done: number, total: number) => `${done} / ${total} 章`,
  noDays: "このプランにはまだ日がありません。",
  editUnavailableTitle: "このプランは編集できません",
  editUnavailableDescription: "所有者だけが編集できます。",
  notOwner: "このプランはあなたのものではありません。",
  planTitleLabel: "プランの題",
  descriptionLabel: "プランの説明",
  descriptionPlaceholder: "どんなプランかの短い説明",
  visibilityLabelText: "公開範囲",
  viewPlan: "プランを見る",
  deletePlan: "削除",
  deletePlanTitle: "このプランを削除しますか？",
  deletePlanDescription: "日と読む章が消えます。元には戻せません。",
  deletePlanConfirm: "削除する",
  deleteDayTitle: "この日を消しますか？",
  deleteDayDescription: "この日の章と文章が消えます。",
  deleteDayConfirm: "消す",
  titleRequired: "題を入力してください。",
  publishNeedsDay: "日を1つ以上足すと、公開できるようになります。",
  noteLabel: "読む人への注記（いつでも書き換えられます）",
  notePlaceholder: "例: 第5日と第6日を入れ違えました。",
  reorderLocked: "読み始めた人がいるため、日の並べ替えと削除はできません。日の中身は直せます。",
  addDay: "＋ 日を足す",
  addingDay: "追加中…",
  appendOnly: "日は末尾にならいつでも足せます。",
  dayActionError: "日の変更を保存できませんでした。もう一度お試しください。",
  dayTitleLabel: (day: number) => `第${day}日の題`,
  dayTitlePlaceholder: "この日の題（任意）",
  devotionalLabel: (day: number) => `第${day}日に添える文章`,
  devotionalPlaceholder: "この日に添える文章（任意）",
  moveUp: (day: number) => `第${day}日を上へ移動`,
  moveDown: (day: number) => `第${day}日を下へ移動`,
  deleteDay: (day: number) => `第${day}日を削除`,
  addChapter: "＋ 章を足す",
  removeChapter: (label: string) => `${label}を外す`,
  chapterLimit: (count: number) => `1日は${count}章までです`,
  retrySave: "保存を再試行",
  findBookLabel: "書を検索",
  findBookPlaceholder: "書をさがす",
  noBooks: "一致する書がありません。",
  backToBooks: "← 書",
  translationLabel: "訳",
  readerTranslation: "読む人の訳",
  chooseChapter: (book: string) => `${book}の章を選ぶ`,
  chapterLoading: "章を読み込んでいます…",
  chapterLoadError: "章を読み込めませんでした。",
  noChapters: "この訳で選べる章がありません。",
  readingEmpty: "読む章がまだありません。",
  chapterLabel: (book: string, chapter: number) => `${book} ${chapter}章`,
  bulkRegion: "まとめてお気に入り",
  pickedVerses: (count: number) => `${count}節を選んでいます`,
  pickVerses: "追加したい節を押してください",
  saveBookmarks: "お気に入りに追加",
  savingBookmarks: "追加しています…",
  bulkPartial: (added: number) => `${added}件を追加しました（残りはお気に入りずみ）`,
  bulkError: "追加できませんでした。もう一度お試しください。",
} : {
  plansTitle: "Reading plans",
  plansDescription: "Follow a day-by-day path through chapters across multiple books.",
  newPlan: "New plan",
  readingPlans: "Plans you're reading",
  myPlans: "My plans",
  myPlansDescription: "Plans you created, including drafts.",
  publicPlans: "Published plans",
  publicPlansDescription: "Plans available to everyone.",
  noPlans: "You haven't created a plan yet.",
  noPublicPlans: "No published plans yet.",
  loadErrorTitle: "Couldn't load reading plans",
  loadErrorDescription: "Check your connection and try again.",
  retry: "Try again",
  visibilityLabel: (visibility: PlanVisibility) => visibility === "public" ? "Public" : visibility === "unlisted" ? "Unlisted" : "Draft",
  visibilityOptions: [
    { value: "private" as const, label: "Draft" },
    { value: "unlisted" as const, label: "Unlisted" },
    { value: "public" as const, label: "Public" },
  ],
  dayCount: (count: number) => `${count} ${count === 1 ? "day" : "days"}`,
  readerCount: (count: number) => `${count} reading`,
  newTitle: "New plan",
  newDescription: "Choose a title to create a draft. You can add days and chapters next.",
  titleLabel: "Title",
  titlePlaceholder: "Example: Revelation in 7 days",
  create: "Create plan",
  creating: "Creating…",
  cancel: "Cancel",
  createError: "Couldn't create the plan. Please try again.",
  createLoginRequired: "Sign in to create a reading plan.",
  login: "Sign in",
  discardNewTitle: "Discard this unfinished plan?",
  discardNewDescription: "The title you entered won't be saved.",
  discardNewConfirm: "Discard",
  unreadableTitle: "This plan isn't available",
  unreadableDescription: "It may have been deleted or made private.",
  backToPlans: "Back to plans",
  edit: "Edit",
  ownerNote: "Note from the author",
  startLoginRequired: "Sign in to start this plan.",
  start: "Start reading",
  resume: "Resume reading",
  reading: "Reading",
  today: (day: number) => `Today is day ${day}`,
  progress: (done: number, total: number) => `${done} of ${total} days completed`,
  restart: "Restart",
  stop: "Stop reading",
  restartTitle: "Restart from the beginning?",
  restartDescription: "All completed marks will be cleared and the schedule will restart today.",
  restartConfirm: "Restart",
  actionError: "Couldn't complete that action. Please try again.",
  dayNumber: (day: number) => `Day ${day}`,
  completed: "Completed ✓",
  markCompleted: "Mark complete",
  markReadingCompleted: (reading: string) => `Mark ${reading} as read`,
  unmarkReadingCompleted: (reading: string) => `Mark ${reading} as unread`,
  dayReadingCount: (done: number, total: number) => `${done} / ${total}`,
  noDays: "This plan doesn't have any days yet.",
  editUnavailableTitle: "This plan can't be edited",
  editUnavailableDescription: "Only its owner can edit it.",
  notOwner: "This plan doesn't belong to you.",
  planTitleLabel: "Plan title",
  descriptionLabel: "Plan description",
  descriptionPlaceholder: "A short description of this plan",
  visibilityLabelText: "Visibility",
  viewPlan: "View plan",
  deletePlan: "Delete",
  deletePlanTitle: "Delete this plan?",
  deletePlanDescription: "Its days and chapter selections will be deleted permanently.",
  deletePlanConfirm: "Delete plan",
  deleteDayTitle: "Delete this day?",
  deleteDayDescription: "Its chapters and text will be deleted.",
  deleteDayConfirm: "Delete day",
  titleRequired: "Enter a title.",
  publishNeedsDay: "Add at least one day before publishing.",
  noteLabel: "Note for readers (you can update it anytime)",
  notePlaceholder: "Example: Days 5 and 6 were reversed.",
  reorderLocked: "Readers have started this plan, so days can't be reordered or deleted. Their contents can still be edited.",
  addDay: "+ Add day",
  addingDay: "Adding…",
  appendOnly: "You can always add a new day at the end.",
  dayActionError: "Couldn't save the day change. Please try again.",
  dayTitleLabel: (day: number) => `Title for day ${day}`,
  dayTitlePlaceholder: "Optional title for this day",
  devotionalLabel: (day: number) => `Text for day ${day}`,
  devotionalPlaceholder: "Optional text for this day",
  moveUp: (day: number) => `Move day ${day} up`,
  moveDown: (day: number) => `Move day ${day} down`,
  deleteDay: (day: number) => `Delete day ${day}`,
  addChapter: "+ Add chapter",
  removeChapter: (label: string) => `Remove ${label}`,
  chapterLimit: (count: number) => `Up to ${count} chapters per day`,
  retrySave: "Retry save",
  findBookLabel: "Search books",
  findBookPlaceholder: "Search for a book",
  noBooks: "No matching books.",
  backToBooks: "← Books",
  translationLabel: "Translation",
  readerTranslation: "Reader's translation",
  chooseChapter: (book: string) => `Choose a chapter from ${book}`,
  chapterLoading: "Loading chapters…",
  chapterLoadError: "Couldn't load chapters.",
  noChapters: "No chapters are available in this translation.",
  readingEmpty: "No chapters have been added yet.",
  chapterLabel: (book: string, chapter: number) => `${book} ${chapter}`,
  bulkRegion: "Bulk favorites",
  pickedVerses: (count: number) => `${count} ${count === 1 ? "verse" : "verses"} selected`,
  pickVerses: "Select the verses you want to favorite",
  saveBookmarks: "Add to favorites",
  savingBookmarks: "Adding…",
  bulkPartial: (added: number) => `Added ${added}; the rest were already favorited`,
  bulkError: "Couldn't add favorites. Please try again.",
};
