/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ログイン。username + password を検証し、成功したらトークンを Cookie にセットする。 */
        post: operations["api_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ログアウト。Cookie の refresh_token をブラックリストに追加し、両方の Cookie を削除する。 */
        post: operations["api_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/auth/me/  現在のログインユーザー情報を返す。PATCH でプロフィール更新。 */
        get: operations["api_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET /api/auth/me/  現在のログインユーザー情報を返す。PATCH でプロフィール更新。 */
        patch: operations["api_auth_me_partial_update"];
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ユーザー登録。
         *     成功するとトークンを HTTP-only Cookie にセットしてログイン状態で返す。
         */
        post: operations["api_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description アクセストークンのリフレッシュ。
         *     Cookie の refresh_token を使い、新しいトークンペアを発行する（rotation あり）。
         *     古い refresh_token はブラックリストに追加される。
         */
        post: operations["api_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/bookmarks/  自分のブックマーク一覧（要認証）
         *     POST /api/bookmarks/  ブックマーク追加（重複は 409）
         */
        get: operations["api_bookmarks_list"];
        put?: never;
        /**
         * @description GET  /api/bookmarks/  自分のブックマーク一覧（要認証）
         *     POST /api/bookmarks/  ブックマーク追加（重複は 409）
         */
        post: operations["api_bookmarks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description DELETE /api/bookmarks/{pk}/  ブックマーク削除（自分のもののみ） */
        delete: operations["api_bookmarks_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 書一覧。認証不要。?translation=和訳 でフィルタ可能。 */
        get: operations["api_books_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/chapters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 指定した書の章一覧。書が存在しない場合は 404。 */
        get: operations["api_books_chapters_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapter_id}/verses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 指定した章の節一覧。章が存在しない場合は 404。 */
        get: operations["api_chapters_verses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/comments/?verse_id=&ordering=new|votes  コメント一覧
         *     POST /api/comments/                                コメント投稿（要認証）
         *
         *     verse_id / chapter_id / book_id のいずれかが必須。
         *     指定なしの場合は空リストを返す。
         */
        get: operations["api_comments_list"];
        put?: never;
        /**
         * @description GET  /api/comments/?verse_id=&ordering=new|votes  コメント一覧
         *     POST /api/comments/                                コメント投稿（要認証）
         *
         *     verse_id / chapter_id / book_id のいずれかが必須。
         *     指定なしの場合は空リストを返す。
         */
        post: operations["api_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description PATCH  /api/comments/{pk}/  body の編集（自分のコメントのみ、削除済みは不可）
         *     DELETE /api/comments/{pk}/  論理削除（自分のコメントのみ）
         *
         *     物理削除は行わず is_deleted=True をセットする。
         */
        delete: operations["api_comments_destroy"];
        options?: never;
        head?: never;
        /**
         * @description PATCH  /api/comments/{pk}/  body の編集（自分のコメントのみ、削除済みは不可）
         *     DELETE /api/comments/{pk}/  論理削除（自分のコメントのみ）
         *
         *     物理削除は行わず is_deleted=True をセットする。
         */
        patch: operations["api_comments_partial_update"];
        trace?: never;
    };
    "/api/comments/{id}/best-answer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description PATCH /api/comments/{pk}/best-answer/  ベストアンサーの設定・解除（質問投稿者のみ）
         *
         *     body: { "answer_comment_id": "<uuid>" }  設定
         *     body: { "answer_comment_id": null }      解除
         */
        patch: operations["api_comments_best_answer_partial_update"];
        trace?: never;
    };
    "/api/comments/{id}/moderate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description DELETE /api/comments/{pk}/moderate/  管理者による強制論理削除
         *     管理者（is_staff=True）のみ利用可能。所有者チェックなし。
         */
        delete: operations["api_comments_moderate_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/report/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/comments/{pk}/report/  通報（要認証、同一コメントへの重複通報は 409） */
        post: operations["api_comments_report_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/upvote/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST   /api/comments/{pk}/upvote/  upvote 追加（要認証、二重投票は 409）
         *     DELETE /api/comments/{pk}/upvote/  upvote 取り消し（未投票の場合は 404）
         */
        post: operations["api_comments_upvote_create"];
        /**
         * @description POST   /api/comments/{pk}/upvote/  upvote 追加（要認証、二重投票は 409）
         *     DELETE /api/comments/{pk}/upvote/  upvote 取り消し（未投票の場合は 404）
         */
        delete: operations["api_comments_upvote_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/mine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/comments/mine/  ログインユーザー自身のコメント一覧（削除済み除く、新着順） */
        get: operations["api_comments_mine_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/qa/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/comments/qa/  Q&Aフラグ付きコメント一覧（認証不要）
         *
         *     ?book_id=   書で絞り込み
         *     ?tag_id=    タグで絞り込み
         */
        get: operations["api_comments_qa_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/notifications/          全通知一覧（新しい順）
         *     GET /api/notifications/?unread=1 未読のみ
         */
        get: operations["api_notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/notifications/{pk}/read/  個別既読 */
        post: operations["api_notifications_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/notifications/read-all/  全既読 */
        post: operations["api_notifications_read_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading-progress/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/reading-progress/  自分の読書進捗一覧（要認証） */
        get: operations["api_reading_progress_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading-progress/save/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/reading-progress/save/  進捗を保存（upsert: user+book 単位で更新or作成） */
        post: operations["api_reading_progress_save_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/search/?q=  節テキストと書名を icontains で検索（口語訳のみ）。 */
        get: operations["api_search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/tags/  タグ一覧（認証不要） */
        get: operations["api_tags_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/translations/  公開中・進行中プロジェクト一覧（認証不要）
         *     POST /api/translations/  プロジェクト作成（要認証）
         */
        get: operations["api_translations_list"];
        put?: never;
        /**
         * @description GET  /api/translations/  公開中・進行中プロジェクト一覧（認証不要）
         *     POST /api/translations/  プロジェクト作成（要認証）
         */
        post: operations["api_translations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET   /api/translations/{id}/  プロジェクト詳細
         *     PATCH /api/translations/{id}/  編集（オーナーのみ）
         */
        get: operations["api_translations_retrieve"];
        /**
         * @description GET   /api/translations/{id}/  プロジェクト詳細
         *     PATCH /api/translations/{id}/  編集（オーナーのみ）
         */
        put: operations["api_translations_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description GET   /api/translations/{id}/  プロジェクト詳細
         *     PATCH /api/translations/{id}/  編集（オーナーのみ）
         */
        patch: operations["api_translations_partial_update"];
        trace?: never;
    };
    "/api/translations/{project_id}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/translations/{id}/activate/  募集開始 draft → active（オーナーのみ） */
        post: operations["api_translations_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description プロジェクト全体コメント or ユニットコメント（GET: 誰でも, POST: 承認済みメンバー） */
        get: operations["api_translations_comments_list"];
        put?: never;
        /** @description プロジェクト全体コメント or ユニットコメント（GET: 誰でも, POST: 承認済みメンバー） */
        post: operations["api_translations_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/comments/{comment_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description DELETE /api/translations/{id}/comments/{cid}/  コメント論理削除（投稿者またはオーナー） */
        delete: operations["api_translations_comments_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/join/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/translations/{id}/join/  参加申請（要認証） */
        post: operations["api_translations_join_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/translations/{id}/members/  メンバー一覧（承認済みメンバーのみ閲覧可） */
        get: operations["api_translations_members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/members/{membership_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description PATCH  /api/translations/{id}/members/{mid}/  承認/拒否（オーナーのみ）
         *     DELETE /api/translations/{id}/members/{mid}/  除名（オーナーのみ）
         */
        delete: operations["api_translations_members_destroy"];
        options?: never;
        head?: never;
        /**
         * @description PATCH  /api/translations/{id}/members/{mid}/  承認/拒否（オーナーのみ）
         *     DELETE /api/translations/{id}/members/{mid}/  除名（オーナーのみ）
         */
        patch: operations["api_translations_members_partial_update"];
        trace?: never;
    };
    "/api/translations/{project_id}/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/translations/{id}/publish/  公開（オーナーのみ） */
        post: operations["api_translations_publish_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/translations/{id}/read/  公開済み翻訳の完了ユニット一覧（誰でも閲覧可） */
        get: operations["api_translations_read_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/units/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/translations/{id}/units/  ユニット一覧
         *     POST /api/translations/{id}/units/  ユニット追加（オーナーのみ）
         */
        get: operations["api_translations_units_list"];
        put?: never;
        /**
         * @description GET  /api/translations/{id}/units/  ユニット一覧
         *     POST /api/translations/{id}/units/  ユニット追加（オーナーのみ）
         */
        post: operations["api_translations_units_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/units/{unit_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET   /api/translations/{id}/units/{uid}/  ユニット詳細
         *     PATCH /api/translations/{id}/units/{uid}/  訳文・ステータス更新（担当者またはオーナー）
         */
        get: operations["api_translations_units_retrieve"];
        /**
         * @description GET   /api/translations/{id}/units/{uid}/  ユニット詳細
         *     PATCH /api/translations/{id}/units/{uid}/  訳文・ステータス更新（担当者またはオーナー）
         */
        put: operations["api_translations_units_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description GET   /api/translations/{id}/units/{uid}/  ユニット詳細
         *     PATCH /api/translations/{id}/units/{uid}/  訳文・ステータス更新（担当者またはオーナー）
         */
        patch: operations["api_translations_units_partial_update"];
        trace?: never;
    };
    "/api/translations/{project_id}/units/{unit_id}/assign/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/translations/{id}/units/{uid}/assign/  担当者割り当て（オーナーのみ） */
        post: operations["api_translations_units_assign_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/units/{unit_id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description プロジェクト全体コメント or ユニットコメント（GET: 誰でも, POST: 承認済みメンバー） */
        get: operations["api_translations_units_comments_list"];
        put?: never;
        /** @description プロジェクト全体コメント or ユニットコメント（GET: 誰でも, POST: 承認済みメンバー） */
        post: operations["api_translations_units_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{project_id}/unpublish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/translations/{id}/unpublish/  公開取り消し → active（オーナーのみ） */
        post: operations["api_translations_unpublish_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/users/<username>/  公開プロフィール（認証不要） */
        get: operations["api_users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/bookmarks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/users/<username>/bookmarks/  ユーザーのお気に入り一覧（認証不要・公開） */
        get: operations["api_users_bookmarks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/users/<username>/comments/  ユーザーのコメント一覧（認証不要） */
        get: operations["api_users_comments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verse-of-the-day/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/verse-of-the-day/  今日の聖句（日付ベースの決定論的選択） */
        get: operations["api_verse_of_the_day_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ヘルスチェックエンドポイント。
         *     DB に接続できる場合は 200、できない場合は 503 を返す。
         *     Better Stack などのアップタイム監視ツールがこのエンドポイントを定期的に叩く。
         */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BestAnswer: {
            /** Format: uuid */
            readonly id: string;
            readonly user: components["schemas"]["CommentAuthor"];
            body: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        Book: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            translation: string;
            /** Format: int64 */
            order: number;
        };
        Bookmark: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            verse?: string | null;
            /** Format: uuid */
            comment?: string | null;
            readonly verse_detail: components["schemas"]["VerseBrief"];
            readonly comment_detail: components["schemas"]["CommentBrief"];
            readonly target_type: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        Chapter: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            book: string;
            /** Format: int64 */
            number: number;
        };
        Comment: {
            /** Format: uuid */
            readonly id: string;
            readonly user: components["schemas"]["CommentAuthor"];
            /** Format: uuid */
            verse?: string | null;
            /** Format: uuid */
            chapter?: string | null;
            /** Format: uuid */
            book?: string | null;
            /** Format: uuid */
            parent?: string | null;
            body: string;
            is_qa?: boolean;
            readonly is_deleted: boolean;
            /** Format: date-time */
            readonly created_at: string;
            readonly vote_count: number;
            readonly tags: components["schemas"]["Tag"][];
            tag_ids?: number[];
        };
        CommentAuthor: {
            /** Format: uuid */
            readonly id: string;
            /**
             * ユーザー名
             * @description この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。
             */
            username: string;
        };
        CommentBrief: {
            /** Format: uuid */
            id: string;
            readonly body: string;
            username: string;
            /** Format: date-time */
            created_at: string;
        };
        CommentEdit: {
            body: string;
        };
        /** @description 自分のコメント一覧用。投稿先の書名・章番号を含む。 */
        MyComment: {
            /** Format: uuid */
            readonly id: string;
            readonly user: components["schemas"]["CommentAuthor"];
            body: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly vote_count: number;
            readonly location_label: string;
        };
        Notification: {
            /** Format: uuid */
            readonly id: string;
            notification_type: components["schemas"]["NotificationTypeEnum"];
            readonly actor_username: string;
            /** Format: uuid */
            readonly comment_id: string;
            readonly comment_body_snippet: string;
            is_read?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `reply` - 返信
         *     * `upvote` - いいね
         * @enum {string}
         */
        NotificationTypeEnum: "reply" | "upvote";
        PatchedCommentEdit: {
            body?: string;
        };
        PatchedTranslationProject: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            description?: string;
            readonly owner_username?: string;
            /** Format: uuid */
            source_book?: string;
            readonly source_book_name?: string;
            target_language?: string;
            status?: components["schemas"]["TranslationProjectStatusEnum"];
            readonly unit_count?: string;
            readonly done_count?: string;
            readonly is_member?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedTranslationUnit: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            verse?: string;
            readonly verse_number?: number;
            readonly verse_text?: string;
            readonly chapter_number?: number;
            /** Format: uuid */
            assigned_to?: string | null;
            readonly assigned_to_username?: string | null;
            body?: string;
            status?: components["schemas"]["TranslationUnitStatusEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        QAComment: {
            /** Format: uuid */
            readonly id: string;
            readonly user: components["schemas"]["CommentAuthor"];
            body: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly vote_count: number;
            readonly tags: components["schemas"]["Tag"][];
            readonly location_label: string;
            readonly book_name: string;
            readonly chapter_number: number | null;
            readonly verse_number: number | null;
            readonly reply_count: number;
            readonly best_answer: components["schemas"]["BestAnswer"];
        };
        ReadingProgress: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            book: string;
            readonly book_name: string;
            /** Format: uuid */
            chapter: string;
            readonly chapter_number: number;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `owner` - オーナー
         *     * `member` - メンバー
         * @enum {string}
         */
        RoleEnum: "owner" | "member";
        Tag: {
            readonly id: number;
            name: string;
        };
        TranslationComment: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            unit?: string | null;
            readonly username: string;
            body: string;
            readonly display_body: string;
            readonly is_deleted: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        TranslationMembership: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly user: string;
            readonly username: string;
            role?: components["schemas"]["RoleEnum"];
            status?: components["schemas"]["TranslationMembershipStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `pending` - 承認待ち
         *     * `approved` - 承認済み
         *     * `rejected` - 拒否
         * @enum {string}
         */
        TranslationMembershipStatusEnum: "pending" | "approved" | "rejected";
        TranslationProject: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string;
            readonly owner_username: string;
            /** Format: uuid */
            source_book: string;
            readonly source_book_name: string;
            target_language: string;
            status?: components["schemas"]["TranslationProjectStatusEnum"];
            readonly unit_count: string;
            readonly done_count: string;
            readonly is_member: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `draft` - 下書き
         *     * `active` - 進行中
         *     * `published` - 公開済み
         * @enum {string}
         */
        TranslationProjectStatusEnum: "draft" | "active" | "published";
        TranslationUnit: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            verse: string;
            readonly verse_number: number;
            readonly verse_text: string;
            readonly chapter_number: number;
            /** Format: uuid */
            assigned_to?: string | null;
            readonly assigned_to_username: string | null;
            body?: string;
            status?: components["schemas"]["TranslationUnitStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `todo` - 未着手
         *     * `in_progress` - 進行中
         *     * `review` - レビュー中
         *     * `done` - 完了
         * @enum {string}
         */
        TranslationUnitStatusEnum: "todo" | "in_progress" | "review" | "done";
        Verse: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            chapter: string;
            /** Format: int64 */
            number: number;
            text: string;
        };
        VerseBrief: {
            /** Format: uuid */
            readonly id: string;
            /** Format: int64 */
            number: number;
            text: string;
            readonly chapter_number: number;
            readonly book_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_bookmarks_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"][];
                };
            };
        };
    };
    api_bookmarks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Bookmark"];
                "application/x-www-form-urlencoded": components["schemas"]["Bookmark"];
                "multipart/form-data": components["schemas"]["Bookmark"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
        };
    };
    api_bookmarks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_books_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"][];
                };
            };
        };
    };
    api_books_chapters_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"][];
                };
            };
        };
    };
    api_chapters_verses_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verse"][];
                };
            };
        };
    };
    api_comments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    api_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Comment"];
                "application/x-www-form-urlencoded": components["schemas"]["Comment"];
                "multipart/form-data": components["schemas"]["Comment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    api_comments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_comments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCommentEdit"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCommentEdit"];
                "multipart/form-data": components["schemas"]["PatchedCommentEdit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentEdit"];
                };
            };
        };
    };
    api_comments_best_answer_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_comments_moderate_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_comments_report_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_comments_upvote_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_comments_upvote_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_comments_mine_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyComment"][];
                };
            };
        };
    };
    api_comments_qa_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QAComment"][];
                };
            };
        };
    };
    api_notifications_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    api_notifications_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_notifications_read_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_reading_progress_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingProgress"][];
                };
            };
        };
    };
    api_reading_progress_save_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_search_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_tags_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
        };
    };
    api_translations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationProject"][];
                };
            };
        };
    };
    api_translations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationProject"];
                "application/x-www-form-urlencoded": components["schemas"]["TranslationProject"];
                "multipart/form-data": components["schemas"]["TranslationProject"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationProject"];
                };
            };
        };
    };
    api_translations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationProject"];
                };
            };
        };
    };
    api_translations_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationProject"];
                "application/x-www-form-urlencoded": components["schemas"]["TranslationProject"];
                "multipart/form-data": components["schemas"]["TranslationProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationProject"];
                };
            };
        };
    };
    api_translations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTranslationProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTranslationProject"];
                "multipart/form-data": components["schemas"]["PatchedTranslationProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationProject"];
                };
            };
        };
    };
    api_translations_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_translations_comments_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationComment"][];
                };
            };
        };
    };
    api_translations_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationComment"];
                "application/x-www-form-urlencoded": components["schemas"]["TranslationComment"];
                "multipart/form-data": components["schemas"]["TranslationComment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationComment"];
                };
            };
        };
    };
    api_translations_comments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_translations_join_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_translations_members_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationMembership"][];
                };
            };
        };
    };
    api_translations_members_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_translations_members_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_translations_publish_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_translations_read_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_translations_units_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationUnit"][];
                };
            };
        };
    };
    api_translations_units_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationUnit"];
                "application/x-www-form-urlencoded": components["schemas"]["TranslationUnit"];
                "multipart/form-data": components["schemas"]["TranslationUnit"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationUnit"];
                };
            };
        };
    };
    api_translations_units_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationUnit"];
                };
            };
        };
    };
    api_translations_units_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationUnit"];
                "application/x-www-form-urlencoded": components["schemas"]["TranslationUnit"];
                "multipart/form-data": components["schemas"]["TranslationUnit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationUnit"];
                };
            };
        };
    };
    api_translations_units_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTranslationUnit"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTranslationUnit"];
                "multipart/form-data": components["schemas"]["PatchedTranslationUnit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationUnit"];
                };
            };
        };
    };
    api_translations_units_assign_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_translations_units_comments_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationComment"][];
                };
            };
        };
    };
    api_translations_units_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationComment"];
                "application/x-www-form-urlencoded": components["schemas"]["TranslationComment"];
                "multipart/form-data": components["schemas"]["TranslationComment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationComment"];
                };
            };
        };
    };
    api_translations_unpublish_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_bookmarks_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"][];
                };
            };
        };
    };
    api_users_comments_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    api_verse_of_the_day_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
