# Generated by Django 5.2.1 on 2026-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0004_verse_text_trgm_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["translation", "order"], name="book_translation_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["canonical_book", "translation"],
                name="book_canonical_trans_idx",
            ),
        ),
    ]
