# Generated by Django 5.2.1 on 2026-09-23 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bible", "0006_tr_pick_scrivener_reading"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("title_ja", models.CharField(blank=True, max_length=300)),
                ("author", models.CharField(max_length=200)),
                ("author_ja", models.CharField(blank=True, max_length=200)),
                ("year", models.SmallIntegerField(blank=True, null=True)),
                (
                    "tradition",
                    models.CharField(
                        choices=[
                            ("jewish", "ユダヤ教"),
                            ("patristic", "教父"),
                            ("medieval", "中世"),
                            ("reformation", "宗教改革"),
                            ("mukyokai", "無教会"),
                        ],
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(max_length=8)),
                ("translator", models.CharField(blank=True, max_length=300)),
                ("source_name", models.CharField(max_length=300)),
                ("source_url", models.URLField(max_length=500)),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("public-domain", "パブリックドメイン"),
                            ("cc0", "CC0"),
                            ("cc-by", "CC BY"),
                            ("cc-by-sa", "CC BY-SA"),
                            ("cc-by-nc", "CC BY-NC"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license_note", models.TextField(blank=True)),
                ("readable", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "commentary_works",
                "ordering": ["year", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                ("heading", models.CharField(blank=True, max_length=500)),
                ("text", models.TextField()),
                ("source_url", models.URLField(blank=True, max_length=500)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="commentary.work",
                    ),
                ),
            ],
            options={
                "db_table": "commentary_sections",
                "ordering": ["order"],
                "unique_together": {("work", "order")},
            },
        ),
        migrations.CreateModel(
            name="PassageLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chapter", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("verse", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "chapter_end",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("verse_end", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("structure", "構造"),
                            ("citation", "引用"),
                            ("ai", "AI判定"),
                        ],
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "canonical_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commentary_links",
                        to="bible.canonicalbook",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="commentary.section",
                    ),
                ),
            ],
            options={
                "db_table": "commentary_passage_links",
                "indexes": [
                    models.Index(
                        fields=["canonical_book", "chapter", "verse"],
                        name="commentary_link_loc_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("method", "ai"), _negated=True),
                            ("confidence__isnull", False),
                            _connector="OR",
                        ),
                        name="commentary_link_ai_has_confidence",
                    )
                ],
            },
        ),
    ]
