# Generated by Django 5.2.1 on 2026-09-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commentary", "0002_chapters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="work",
            options={"ordering": ["year", "author", "order", "slug"]},
        ),
        migrations.AddField(
            model_name="commentarychapter",
            name="title_en",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="work",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
