# Generated by Django 5.2.1 on 2026-09-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commentary", "0003_english_titles_and_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="license_note_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="work",
            name="translator_en",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
