# Generated by Django 5.2.1 on 2026-09-03 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_day_marks_to_readings(apps, schema_editor):
    """
    これまでの「その日を読み終えた」印を、その日の章ぜんぶの印に置き換える。

    これが無いと、すでに読み終えた日を開いたときに章の印が空になり、
    読み直しを迫られたように見えてしまう。
    """
    PlanDayProgress = apps.get_model("plans", "PlanDayProgress")
    PlanReadingProgress = apps.get_model("plans", "PlanReadingProgress")

    marks = [
        PlanReadingProgress(subscription_id=mark.subscription_id, reading_id=reading_id)
        for mark in PlanDayProgress.objects.all().prefetch_related("day__readings")
        for reading_id in mark.day.readings.values_list("id", flat=True)
    ]
    PlanReadingProgress.objects.bulk_create(marks, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanReadingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='plans.plandayreading')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='plans.plansubscription')),
            ],
            options={
                'db_table': 'plan_reading_progress',
                'constraints': [models.UniqueConstraint(fields=('subscription', 'reading'), name='unique_subscription_reading_progress')],
            },
        ),
        # 戻すときは何もしない。章ごとの表ごと消えるため。
        migrations.RunPython(copy_day_marks_to_readings, migrations.RunPython.noop),
    ]
