# Generated by Django 5.2.1 on 2026-09-22 15:40

from django.db import migrations, models


def unlisted_to_private(apps, schema_editor):
    """限定公開をなくすので、限定公開だったものは下書きに戻す。

    公開にすると、書いた人が一覧に出すつもりのなかったものまで出てしまう。
    見える人が減る側（下書き）に倒しておけば、書いた人が選び直せる。
    """
    apps.get_model("plans", "Plan").objects.filter(visibility="unlisted").update(visibility="private")


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_search_indexes'),
    ]

    operations = [
        migrations.RunPython(unlisted_to_private, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='plan',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', max_length=12),
        ),
    ]
