# Generated by Django 5.2.1 on 2026-09-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0006_tr_pick_scrivener_reading"),
        ("commentary", "0002_chapters"),
        ("plans", "0004_drop_unlisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="plandayreading",
            name="commentary_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_readings",
                to="commentary.work",
            ),
        ),
        migrations.AlterField(
            model_name="plandayreading",
            name="canonical_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_readings",
                to="bible.canonicalbook",
            ),
        ),
        migrations.AddConstraint(
            model_name="plandayreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("canonical_book__isnull", False),
                        ("commentary_work__isnull", True),
                    ),
                    models.Q(
                        ("canonical_book__isnull", True),
                        ("commentary_work__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="plan_reading_one_book",
            ),
        ),
    ]
