# Generated by Django 5.2.1 on 2026-08-01 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bible", "0004_verse_text_trgm_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "db_table": "article_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("unlisted", "Unlisted"),
                            ("public", "Public"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=12,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="articles.articletag"
                    ),
                ),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=5000)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="articles.article",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="articles.articlecomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "article_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleCitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("inline", "Inline reference"),
                            ("block", "Block quote"),
                        ],
                        max_length=8,
                    ),
                ),
                ("chapter_number", models.PositiveSmallIntegerField()),
                (
                    "verse_number_start",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "verse_number_end",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("translation", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="articles.article",
                    ),
                ),
                (
                    "canonical_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="article_citations",
                        to="bible.canonicalbook",
                    ),
                ),
            ],
            options={
                "db_table": "article_citations",
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=[
                            "canonical_book",
                            "chapter_number",
                            "verse_number_start",
                        ],
                        name="article_citation_location",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "raw"), name="unique_article_citation_raw"
                    )
                ],
            },
        ),
    ]
