# Generated by Django 5.2.1 on 2026-09-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_drop_unlisted"),
        ("bible", "0006_tr_pick_scrivener_reading"),
        ("commentary", "0002_chapters"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecitation",
            name="commentary_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_citations",
                to="commentary.work",
            ),
        ),
        migrations.AlterField(
            model_name="articlecitation",
            name="canonical_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_citations",
                to="bible.canonicalbook",
            ),
        ),
        migrations.AddIndex(
            model_name="articlecitation",
            index=models.Index(
                fields=["commentary_work", "chapter_number", "verse_number_start"],
                name="article_citation_commentary",
            ),
        ),
        migrations.AddConstraint(
            model_name="articlecitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("canonical_book__isnull", False),
                        ("commentary_work__isnull", True),
                    ),
                    models.Q(
                        ("canonical_book__isnull", True),
                        ("commentary_work__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="article_citation_one_book",
            ),
        ),
    ]
