/** 設定画面の文言。区画ごとに切り出した部品からも読むので、別ファイルにしてある。 */
export const settingsCopy = {
  ja: {
    title: "アカウント設定",
    lead: "ログイン情報、通知、セッションとアカウントを管理します。",
    nav: "設定セクション",
    identity: "ユーザー情報",
    identityDesc: "ユーザー名またはメールアドレスを変更するには、現在のパスワードが必要です。",
    username: "ユーザー名",
    email: "メールアドレス",
    currentPassword: "現在のパスワード",
    saveIdentity: "ユーザー情報を保存",
    identitySaved: "ユーザー情報を更新しました。",
    oauthIdentity: "OAuthのみで登録したアカウントでは、パスワード確認が必要な情報をこの画面から変更できません。",
    notifications: "通知",
    notificationsDesc: "受け取りたい通知方法を選択できます。",
    emailNotifications: "メール通知",
    emailNotificationsDesc: "重要なアクティビティを登録メールアドレスで受け取ります。",
    inAppNotifications: "アプリ内通知",
    inAppNotificationsDesc: "NeON Church内の通知一覧にアクティビティを表示します。",
    saveNotifications: "通知設定を保存",
    notificationsSaved: "通知設定を更新しました。",
    password: "パスワード",
    passwordDesc: "変更すると他のすべての更新トークンが失効し、この端末に新しいセッションが発行されます。",
    newPassword: "新しいパスワード",
    confirmPassword: "新しいパスワード（確認）",
    passwordHint: "8文字以上で設定してください。",
    passwordMismatch: "新しいパスワードが一致しません。",
    changePassword: "パスワードを変更",
    passwordChanged: "パスワードを変更し、他のセッションを無効にしました。",
    oauthPassword: "このアカウントはOAuthでログインしています。パスワード変更は利用できません。",
    sessions: "ログイン中のセッション",
    sessionsDesc: "有効な更新トークンを確認し、不要なセッションを無効にできます。",
    currentSession: "現在のセッション",
    otherSession: "別のセッション",
    issued: "開始",
    expires: "有効期限",
    revoke: "無効にする",
    revokeOthers: "他のセッションをすべて無効にする",
    revokeTitle: "セッションを無効にしますか？",
    revokeDesc: "対象の端末では、アクセストークンの期限後に再ログインが必要になります。",
    revokeOthersTitle: "他のセッションをすべて無効にしますか？",
    revokeOthersDesc: "現在の端末以外で再ログインが必要になります。",
    sessionRevoked: "セッションを無効にしました。",
    noSessions: "有効なセッションはありません。",
    danger: "アカウント削除",
    dangerDesc: "投稿を含む関連データが削除される可能性があります。この操作は取り消せません。",
    confirmUsername: "確認のためユーザー名を入力",
    deleteAccount: "アカウントを削除",
    deleteTitle: "アカウントを完全に削除しますか？",
    deleteDesc: "この操作は取り消せません。入力内容を確認して削除してください。",
    deleteConfirm: "完全に削除",
    cancel: "キャンセル",
    save: "保存中...",
    loadFailed: "設定を読み込めませんでした",
    loadFailedDesc: "通信状態を確認して、もう一度お試しください。",
    retry: "再試行",
    actionFailed: "操作に失敗しました。もう一度お試しください。",
  },
  en: {
    title: "Account settings",
    lead: "Manage your sign-in details, notifications, sessions, and account.",
    nav: "Settings sections",
    identity: "Account details",
    identityDesc: "Your current password is required to change your username or email address.",
    username: "Username",
    email: "Email address",
    currentPassword: "Current password",
    saveIdentity: "Save account details",
    identitySaved: "Your account details were updated.",
    oauthIdentity: "Accounts created only through OAuth cannot change password-protected details here.",
    notifications: "Notifications",
    notificationsDesc: "Choose how you want to receive notifications.",
    emailNotifications: "Email notifications",
    emailNotificationsDesc: "Receive important activity at your registered email address.",
    inAppNotifications: "In-app notifications",
    inAppNotificationsDesc: "Show activity in your NeON Church notification list.",
    saveNotifications: "Save notification preferences",
    notificationsSaved: "Your notification preferences were updated.",
    password: "Password",
    passwordDesc: "Changing it revokes every existing refresh session and issues a new session on this device.",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    passwordHint: "Use at least 8 characters.",
    passwordMismatch: "The new passwords do not match.",
    changePassword: "Change password",
    passwordChanged: "Your password was changed and other sessions were revoked.",
    oauthPassword: "This account signs in with OAuth. Password change is unavailable.",
    sessions: "Active sessions",
    sessionsDesc: "Review active refresh tokens and revoke sessions you no longer need.",
    currentSession: "Current session",
    otherSession: "Other session",
    issued: "Started",
    expires: "Expires",
    revoke: "Revoke",
    revokeOthers: "Revoke all other sessions",
    revokeTitle: "Revoke this session?",
    revokeDesc: "That device will need to sign in again after its access token expires.",
    revokeOthersTitle: "Revoke all other sessions?",
    revokeOthersDesc: "Every device except this one will need to sign in again.",
    sessionRevoked: "The session was revoked.",
    noSessions: "There are no active sessions.",
    danger: "Delete account",
    dangerDesc: "Related data, including posts, may be deleted. This action cannot be undone.",
    confirmUsername: "Enter your username to confirm",
    deleteAccount: "Delete account",
    deleteTitle: "Permanently delete your account?",
    deleteDesc: "This cannot be undone. Check the information you entered before deleting.",
    deleteConfirm: "Delete permanently",
    cancel: "Cancel",
    save: "Saving...",
    loadFailed: "Could not load settings",
    loadFailedDesc: "Check your connection and try again.",
    retry: "Try again",
    actionFailed: "The action failed. Please try again.",
  },
} as const;
