# Generated by Django 5.2.1 on 2026-08-02 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bible", "0005_book_book_translation_order_idx_and_more"),
        ("comments", "0016_comment_comment_location_recent_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=5000)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qa_answers",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "verse_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "source_translation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(max_length=5000)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "best_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_answer_for",
                        to="qa.answer",
                    ),
                ),
                (
                    "canonical_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="bible.canonicalbook",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="questions", to="comments.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qa_questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="qa.question",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["best_answer", "-created_at"], name="qa_question_answered_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=[
                    "canonical_book",
                    "chapter_number",
                    "verse_number",
                    "-created_at",
                ],
                name="qa_question_location_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("chapter_number__isnull", True),
                    ("verse_number__isnull", False),
                    _negated=True,
                ),
                name="qa_question_location_grain_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question", "created_at"], name="qa_answer_question_idx"
            ),
        ),
    ]
