# Generated by Django 5.2.1 on 2026-09-23 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0006_tr_pick_scrivener_reading"),
        ("commentary", "0002_chapters"),
        ("comments", "0019_remove_comment_comment_location_grain_valid_and_more"),
        ("qa", "0002_question_search_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="commentary_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="commentary.work",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="canonical_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="bible.canonicalbook",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=[
                    "commentary_work",
                    "chapter_number",
                    "verse_number",
                    "-created_at",
                ],
                name="qa_question_commentary_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("canonical_book__isnull", False),
                        ("commentary_work__isnull", True),
                    ),
                    models.Q(
                        ("canonical_book__isnull", True),
                        ("commentary_work__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="qa_question_one_book",
            ),
        ),
    ]
