# Generated by Django 5.2.1 on 2026-07-11 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_alter_book_canonical_book'),
        ('bookmarks', '0002_bookmark_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='canonical_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookmarks', to='bible.canonicalbook'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='chapter_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='verse_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
