# Generated by Django 5.2.1 on 2026-07-11 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_alter_book_canonical_book'),
        ('bookmarks', '0003_bookmark_canonical_book_bookmark_chapter_number_and_more'),
        ('comments', '0012_comment_translation_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_book__isnull', False), ('chapter_number__isnull', False), ('verse_number__isnull', False)), fields=('user', 'canonical_book', 'chapter_number', 'verse_number'), name='unique_user_location_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', False), ('canonical_book__isnull', True), ('chapter_number__isnull', True), ('verse_number__isnull', True)), models.Q(('comment__isnull', True), ('canonical_book__isnull', False), ('chapter_number__isnull', False), ('verse_number__isnull', False)), _connector='OR'), name='bookmark_comment_xor_location'),
        ),
    ]
