# Generated by Django 5.2.1 on 2026-07-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_bookmark_unique_user_location_bookmark_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_user_verse_bookmark',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='verse',
        ),
    ]
