# Generated by Django 5.2.1 on 2026-07-14 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_verse_text_trgm_index'),
        ('bookmarks', '0005_remove_bookmark_unique_user_verse_bookmark_and_more'),
        ('comments', '0015_comment_body_trgm_index'),
        ('translations', '0005_translationlibraryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='bookmark_comment_xor_location',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='translation_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='translations.translationproject'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('translation_project__isnull', False)), fields=('user', 'translation_project'), name='unique_user_project_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_book__isnull', False), ('chapter_number__isnull', False), ('verse_number__isnull', True)), fields=('user', 'canonical_book', 'chapter_number'), name='unique_user_chapter_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_book__isnull', False), ('chapter_number__isnull', True), ('verse_number__isnull', True)), fields=('user', 'canonical_book'), name='unique_user_book_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', False), ('translation_project__isnull', True), ('canonical_book__isnull', True), ('chapter_number__isnull', True), ('verse_number__isnull', True)), models.Q(('translation_project__isnull', False), ('comment__isnull', True), ('canonical_book__isnull', True), ('chapter_number__isnull', True), ('verse_number__isnull', True)), models.Q(('canonical_book__isnull', False), ('comment__isnull', True), ('translation_project__isnull', True), models.Q(('verse_number__isnull', True), ('chapter_number__isnull', False), _connector='OR')), _connector='OR'), name='bookmark_single_target'),
        ),
    ]
