# Generated by Django 5.2.1 on 2026-08-01 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0005_book_book_translation_order_idx_and_more"),
        ("bookmarks", "0006_remove_bookmark_bookmark_comment_xor_location_and_more"),
        ("comments", "0015_comment_body_trgm_index"),
        ("translations", "0005_translationlibraryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-created_at"], name="bookmark_user_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "canonical_book", "chapter_number"],
                name="bookmark_user_location_idx",
            ),
        ),
    ]
