# Generated by Django 5.2.1 on 2026-09-23 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0006_tr_pick_scrivener_reading"),
        ("bookmarks", "0007_bookmark_bookmark_user_recent_idx_and_more"),
        ("commentary", "0002_chapters"),
        ("comments", "0018_remove_comment_comment_qa_recent_idx_and_more"),
        ("translations", "0006_project_search_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="bookmark_single_target",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="commentary_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookmarks",
                to="commentary.work",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("commentary_work__isnull", False),
                    ("chapter_number__isnull", False),
                    ("verse_number__isnull", False),
                ),
                fields=("user", "commentary_work", "chapter_number", "verse_number"),
                name="unique_user_commentary_section_bookmark",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("commentary_work__isnull", False),
                    ("chapter_number__isnull", False),
                    ("verse_number__isnull", True),
                ),
                fields=("user", "commentary_work", "chapter_number"),
                name="unique_user_commentary_chapter_bookmark",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("commentary_work__isnull", False),
                    ("chapter_number__isnull", True),
                    ("verse_number__isnull", True),
                ),
                fields=("user", "commentary_work"),
                name="unique_user_commentary_work_bookmark",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("comment__isnull", False),
                        ("translation_project__isnull", True),
                        ("canonical_book__isnull", True),
                        ("commentary_work__isnull", True),
                        ("chapter_number__isnull", True),
                        ("verse_number__isnull", True),
                    ),
                    models.Q(
                        ("translation_project__isnull", False),
                        ("comment__isnull", True),
                        ("canonical_book__isnull", True),
                        ("commentary_work__isnull", True),
                        ("chapter_number__isnull", True),
                        ("verse_number__isnull", True),
                    ),
                    models.Q(
                        ("canonical_book__isnull", False),
                        ("commentary_work__isnull", True),
                        ("comment__isnull", True),
                        ("translation_project__isnull", True),
                        models.Q(
                            ("verse_number__isnull", True),
                            ("chapter_number__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("commentary_work__isnull", False),
                        ("canonical_book__isnull", True),
                        ("comment__isnull", True),
                        ("translation_project__isnull", True),
                        models.Q(
                            ("verse_number__isnull", True),
                            ("chapter_number__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="bookmark_single_target",
            ),
        ),
    ]
