# Generated by Django 5.2.1 on 2026-05-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationproject",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("現代日本語", "現代日本語"),
                    ("やさしい日本語", "やさしい日本語"),
                    ("口語日本語", "口語日本語"),
                    ("文語日本語", "文語日本語"),
                    ("English", "English"),
                    ("한국어", "한국어"),
                    ("中文（简体）", "中文（简体）"),
                    ("中文（繁體）", "中文（繁體）"),
                ],
                max_length=50,
            ),
        ),
    ]
