# Generated by Django 5.2.1 on 2026-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0002_target_language_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationproject",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("ja", "日本語"),
                    ("en", "English"),
                    ("ko", "한국어"),
                    ("zh-Hans", "中文（简体）"),
                    ("zh-Hant", "中文（繁體）"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("es", "Español"),
                    ("pt", "Português"),
                    ("ar", "العربية"),
                ],
                max_length=20,
            ),
        ),
    ]
