# Generated by Django 5.2.1 on 2026-05-24 22:18

import uuid
from django.db import migrations, models


def create_initial_languages(apps, schema_editor):
    Language = apps.get_model("translations", "Language")
    initial = [
        ("ja", "日本語", 0),
        ("en", "English", 1),
        ("ko", "한국어", 2),
        ("zh-Hans", "中文（简体）", 3),
        ("zh-Hant", "中文（繁體）", 4),
        ("fr", "Français", 5),
        ("de", "Deutsch", 6),
        ("es", "Español", 7),
        ("pt", "Português", 8),
        ("ar", "العربية", 9),
    ]
    for tag, label, order in initial:
        Language.objects.create(tag=tag, label=label, order=order)


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0003_target_language_ietf_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "translation_languages",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="translationproject",
            name="target_language",
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(create_initial_languages, migrations.RunPython.noop),
    ]
