# Generated by Django 5.2.1 on 2026-06-28 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_add_language_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLibraryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='translations.translationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'translation_library_entries',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_library')],
            },
        ),
    ]
