# Generated by Django 5.2.1 on 2026-05-05 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0001_initial"),
        ("comments", "0003_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="bible.book",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="bible.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="verse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="bible.verse",
            ),
        ),
    ]
