# Generated by Django 5.2.1 on 2026-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_add_chapter_book_to_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_qa",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
