# Generated by Django 5.2.1 on 2026-05-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_add_is_qa_to_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "comment_tags",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="comments.tag"
            ),
        ),
    ]
