# Generated by Django 5.2.1 on 2026-05-11 14:08

from django.db import migrations

TAGS = ["質問", "感想", "解説", "証し", "祈り", "考察"]


def seed_tags(apps, schema_editor):
    Tag = apps.get_model("comments", "Tag")
    for name in TAGS:
        Tag.objects.get_or_create(name=name)


def unseed_tags(apps, schema_editor):
    Tag = apps.get_model("comments", "Tag")
    Tag.objects.filter(name__in=TAGS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_add_tag_model"),
    ]

    operations = [
        migrations.RunPython(seed_tags, unseed_tags),
    ]
