# Generated by Django 5.2.1 on 2026-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0010_add_title_to_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam"),
                    ("offensive", "Offensive content"),
                    ("misinformation", "Misinformation"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
