# Generated by Django 5.2.1 on 2026-06-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_alter_report_reason'),
        ('translations', '0005_translationlibraryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='translation_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bible_comments', to='translations.translationproject'),
        ),
    ]
