# Generated by Django 5.2.1 on 2026-07-12 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_alter_book_canonical_book'),
        ('comments', '0012_comment_translation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='canonical_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='bible.canonicalbook'),
        ),
        migrations.AddField(
            model_name='comment',
            name='chapter_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='source_translation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='verse_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
