# Generated by Django 5.2.1 on 2026-07-12 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_alter_book_canonical_book'),
        ('comments', '0013_comment_canonical_book_comment_chapter_number_and_more'),
        ('translations', '0005_translationlibraryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='verse',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('canonical_book__isnull', False), models.Q(('chapter_number__isnull', True), ('verse_number__isnull', False), _negated=True)), name='comment_location_grain_valid'),
        ),
    ]
