# Generated by Django 5.2.1 on 2026-08-01 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0005_book_book_translation_order_idx_and_more"),
        ("comments", "0015_comment_body_trgm_index"),
        ("translations", "0005_translationlibraryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=[
                    "canonical_book",
                    "chapter_number",
                    "verse_number",
                    "-created_at",
                ],
                name="comment_location_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_qa", "parent", "-created_at"], name="comment_qa_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent", "-created_at"], name="comment_replies_recent_idx"
            ),
        ),
    ]
