# Generated by Django 5.2.1 on 2026-08-02 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0016_comment_comment_location_recent_idx_and_more"),
        ("qa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="report",
            name="unique_reporter_comment_report",
        ),
        migrations.AddField(
            model_name="report",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="qa.answer",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="qa.question",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="comments.comment",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("reporter", "comment"),
                name="unique_reporter_comment_report",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("question__isnull", False)),
                fields=("reporter", "question"),
                name="unique_reporter_question_report",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("answer__isnull", False)),
                fields=("reporter", "answer"),
                name="unique_reporter_answer_report",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("answer__isnull", True),
                        ("comment__isnull", False),
                        ("question__isnull", True),
                    ),
                    models.Q(
                        ("answer__isnull", True),
                        ("comment__isnull", True),
                        ("question__isnull", False),
                    ),
                    models.Q(
                        ("answer__isnull", False),
                        ("comment__isnull", True),
                        ("question__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="report_has_exactly_one_target",
            ),
        ),
    ]
