# Generated by Django 5.2.1 on 2026-08-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0017_remove_report_unique_reporter_comment_report_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="comment_qa_recent_idx",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="best_answer",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="is_qa",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="title",
        ),
    ]
