# Generated by Django 5.2.1 on 2026-09-23 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0006_tr_pick_scrivener_reading"),
        ("commentary", "0002_chapters"),
        ("comments", "0018_remove_comment_comment_qa_recent_idx_and_more"),
        ("translations", "0006_project_search_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="comment_location_grain_valid",
        ),
        migrations.AddField(
            model_name="comment",
            name="commentary_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="commentary.work",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=[
                    "commentary_work",
                    "chapter_number",
                    "verse_number",
                    "-created_at",
                ],
                name="comment_commentary_recent_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("canonical_book__isnull", False),
                            ("commentary_work__isnull", True),
                        ),
                        models.Q(
                            ("canonical_book__isnull", True),
                            ("commentary_work__isnull", False),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("chapter_number__isnull", True),
                        ("verse_number__isnull", False),
                        _negated=True,
                    ),
                ),
                name="comment_location_grain_valid",
            ),
        ),
    ]
