# Generated by Django 5.2.1 on 2026-05-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_security_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmarks_visibility",
            field=models.CharField(
                choices=[("private", "非公開"), ("public", "公開")],
                default="private",
                max_length=10,
            ),
        ),
    ]
