# Generated by Django 5.2.1 on 2026-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_avatar_from_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bookmarks_visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="private",
                max_length=10,
            ),
        ),
    ]
