# Generated by Django 5.2.1 on 2026-07-15 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bible", "0004_verse_text_trgm_index"),
        ("translations", "0005_translationlibraryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotifTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "motif_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompiledBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=240, unique=True)),
                ("description", models.TextField(blank=True)),
                ("annotation", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("unlisted", "Unlisted"),
                            ("public", "Public"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=12,
                    ),
                ),
                (
                    "forked_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="compilations.compiledbook",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiled_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "motifs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compiled_books",
                        to="compilations.motiftag",
                    ),
                ),
            ],
            options={
                "db_table": "compiled_books",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CompiledChapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=200)),
                ("introduction", models.TextField(blank=True)),
                ("annotation", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="compilations.compiledbook",
                    ),
                ),
                (
                    "motifs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compiled_chapters",
                        to="compilations.motiftag",
                    ),
                ),
            ],
            options={
                "db_table": "compiled_chapters",
                "ordering": ["order", "number"],
            },
        ),
        migrations.CreateModel(
            name="CompiledVerse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verse_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("bible_verse", "Bible verse"),
                            ("translation_unit", "Translation unit"),
                            ("compiled_verse", "Compiled verse"),
                            ("note", "Note"),
                        ],
                        default="bible_verse",
                        max_length=24,
                    ),
                ),
                ("body_snapshot", models.TextField()),
                ("source_label", models.CharField(blank=True, max_length=240)),
                ("curator_note", models.TextField(blank=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="compilations.compiledbook",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verses",
                        to="compilations.compiledchapter",
                    ),
                ),
                (
                    "source_compiled_verse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compiled_occurrences",
                        to="compilations.compiledverse",
                    ),
                ),
                (
                    "source_translation_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compiled_occurrences",
                        to="translations.translationunit",
                    ),
                ),
                (
                    "source_verse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compiled_occurrences",
                        to="bible.verse",
                    ),
                ),
                (
                    "motifs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compiled_verses",
                        to="compilations.motiftag",
                    ),
                ),
            ],
            options={
                "db_table": "compiled_verses",
                "ordering": ["chapter__order", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompiledComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=5000)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="compilations.compiledbook",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="compilations.compiledchapter",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="compilations.compiledcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiled_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="compilations.compiledverse",
                    ),
                ),
            ],
            options={
                "db_table": "compiled_comments",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("book__isnull", False),
                                ("chapter__isnull", True),
                                ("verse__isnull", True),
                            ),
                            models.Q(
                                ("book__isnull", True),
                                ("chapter__isnull", False),
                                ("verse__isnull", True),
                            ),
                            models.Q(
                                ("book__isnull", True),
                                ("chapter__isnull", True),
                                ("verse__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="compiled_comment_single_target",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="compiledchapter",
            constraint=models.UniqueConstraint(
                fields=("book", "number"), name="unique_compiled_chapter_number"
            ),
        ),
    ]
