# Generated by Django 5.2.1 on 2026-07-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiledbook',
            name='tray_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
